### PR TITLE
ci: change to use sha from branch name

### LINKED ISSUE #879: lint commit messages doesn't work for PRs from forks
https://github.com/openameba/spindle/actions/runs/7316050126/job/19937765185?pr=877

```
Run npx commitlint --from "$(git merge-base "origin/${GITHUB_BASE_REF}" "origin/${GITHUB_HEAD_REF}")" --to "origin/${GITHUB_HEAD_REF}" --verbose
fatal: Not a valid object name origin/visual-regression-test-with-permissions
/home/runner/work/spindle/spindle/node_modules/@commitlint/cli/lib/cli.js:114
        throw err;
        ^

Error: fatal: ambiguous argument 'origin/visual-regression-test-with-permissions': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

For forks, the `GITHUB_HEAD_REF` will not be present in `origin`.

### PR DESCRIPTION
**Pull request by sasaplus1**
This PR fixes #879

### CODE REVIEW

**Comment by herablog** [comment]
Looks good, can you make a PR from a forked repo to test?

**Comment by sasaplus1** [comment]
Do we test after merging this PR?

**Comment by sasaplus1** [comment]
Ah, I didn't know how to fork by target branch. #881

**Comment by herablog** [comment]
Yep, we can test it before merging!

🟢  https://github.com/openameba/spindle/actions/runs/7327227031

**Review by herablog — APPROVED** [review]
エンジニアを褒めるネコ:仕事はやい

**Pull request merged**
